name: Backup Repositories to GitLab and S3
on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup backup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git unzip
          chmod +x ./scripts/backup-repos.sh
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Run backup script
        run: ./scripts/backup-repos.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT_BACKUP }}
          GH_ORG: ${{ secrets.GH_ORG }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GL_GROUP: ${{ secrets.GL_GROUP }}
          GL_GROUP_ID: ${{ secrets.GL_GROUP_ID }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      
      - name: Upload backup report
        if: always()  # This ensures the artifact is uploaded even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: backup-report
          path: backup-report.txt
          retention-days: 7