name: Backup Repositories to GitLab

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:     # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup backup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git
          chmod +x ./scripts/backup-repos.sh

      - name: Run backup script
        run: ./scripts/backup-repos.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT_BACKUP }}
          GH_ORG: ${{ secrets.GH_ORG }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GL_GROUP: ${{ secrets.GL_GROUP }}
          GL_GROUP_ID: ${{ secrets.GL_GROUP_ID }}

      - name: Upload backup report
        uses: actions/upload-artifact@v3
        with:
          name: backup-report
          path: backup-report.txt
          retention-days: 7